### PR TITLE
Tag filter

### PR DESCRIPTION
**Pull request by spirali**
Filtering in left panel by one or more tags

Partially solves: #37 

image

### CODE REVIEW

**Comment by jas-ho** [comment]
@spirali here is what those damn users do :cold_sweat: (in this case, it was me)
image

I wanted to just tag-ify my whole hydra config, so I could easily filter by different hyperparam settings. This produces _a lot_ of tags which ends up not looking so nice. just wanted to share so you're aware of how this might end up being used

**Comment by jas-ho** [comment]
@spirali one thing which might make a difference UX-wise would be to distinguish between

-  tags which _differentiate_ between different root contexts (those are actually useful for filtering and should be visually prominent) and
- tags which _are the same_ across all root contexts (those are not useful for filtering and could be hidden or visually attenuated)

**Comment by spirali** [comment]
At first sight it seems to me that you are abusing tags for something that should be in inputs. We probably need filtering based on inputs. On the other way, I am also thinking about something like (in Python API):

```python
  # This exists and show full storage in Data browser
  storage.display() 

  # My proposal: Shows only filtered values in Data browser, 
  # it also registers new or running contexts but only if it passes the filter
  storage.filter(lambda ctx: ctx.inputs["rounds"] == 2).display()  
```

**Comment by jas-ho** [comment]
agree that this is probably abuse of tags. it really just bc it's the only filtering we have right now :grimacing:

**Comment by jas-ho** [comment]
the Python solution looks fairly general but it would be great to have filtering in the front-end (imagine a use-case where you open a large number of dialogues for inspection by the public using a hosted version of the context browser)

**Comment by spirali** [comment]
I am now working on documentation. But I will try to implement some more advanced filtering in the end of the week. I was actually also bitten but overwhelmingly many contexts :)

**Pull request merged**
